name: BigQuery-Integration

on:
  push:
    branches:
      - main

env:
  BIG_QUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.BIGQUERY_PROJECT }}
          service_account_key: ${{ secrets.BQ_SERVICE_ACCOUNT_64 }}
          export_default_credentials: true
      - name: Integration Tests
        run: sbt -v -Dfile.encoding=UTF-8 +it:test
      #- name: Coverage Report
      #  run: sbt -v -Dfile.encoding=UTF-8 coverageReport
      #- name: Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    verbose: false # optional (default = false)
      #    flags: bq-integration
