name: BigQuery-Integration

on:
  push:
    branches:
      - main

env:
  BIG_QUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  it-test:
    name: Build and BQ IT Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.8"
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.BIGQUERY_PROJECT }}
          service_account_key: ${{ secrets.BQ_SERVICE_ACCOUNT_64 }}
          export_default_credentials: true
      - name: Integration Tests
        run: sbt -v -Dfile.encoding=UTF-8 +bigquery/IntegrationTest/test

  coverage-it:
    name: Code Coverage IT Tests
    strategy:
      matrix:
        scala: [2.12.20, 2.13.17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.8"
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.BIGQUERY_PROJECT }}
          service_account_key: ${{ secrets.BQ_SERVICE_ACCOUNT_64 }}
          export_default_credentials: true
      - name: Integration Tests
        run: sbt ++${{ matrix.scala }} clean coverage bigquery/IntegrationTest/test
      - name: Coverage Report
        run: sbt ++${{ matrix.scala }} coverageReport
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false # optional (default = false)
          flags: bq-integration
